export const currentUser = {
  _id: "u01",
  userId: "01",
  name: "John Doe",
  username: "johndoe",
  email: "john@example.com",
  avatar: "https://i.pravatar.cc/300",
  gender: "male",
  status: "active",
  bio: "lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
  friends: ["u02", "u03", "u04", "u05", "u06", "u07", "u08", "u09", "u10"],
};

export const friends = [
  {
    _id: "u02",
    userId: "02",
    name: "Jane Doe",
    username: "janedoe",
    email: "jane@example.com",
    avatar: "https://i.pravatar.cc/300",
    gender: "female",
    status: "active",
    bio: "lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    msgCount: 3,
  },
  {
    _id: "u03",
    userId: "03",
    name: "Bob Smith",
    username: "bobsmith",
    email: "bob@example.com",
    avatar: "https://i.pravatar.cc/300",
    gender: "male",
    status: "active",
    bio: "lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    msgCount: 2,
  },
  {
    _id: "u04",
    userId: "04",
    name: "Alice Johnson",
    username: "alicejohnson",
    email: "alice@example.com",
    avatar: "https://i.pravatar.cc/300",
    gender: "female",
    status: "active",
    bio: "lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    msgCount: 1,
  },
  {
    _id: "u05",
    userId: "05",
    name: "Charlie Brown",
    username: "charliebrown",
    email: "charlie@example.com",
    avatar: "https://i.pravatar.cc/300",
    gender: "male",
    status: "active",
    bio: "lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    msgCount: 0,
  },
  {
    _id: "u06",
    userId: "06",
    name: "Jane Doe",
    username: "janedoe",
    email: "jane@example.com",
    avatar: "https://i.pravatar.cc/300",
    gender: "female",
    status: "active",
    bio: "lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    msgCount: 0,
  },
  {
    _id: "u07",
    userId: "07",
    name: "Bob Smith",
    username: "bobsmith",
    email: "bob@example.com",
    avatar: "https://i.pravatar.cc/300",
    gender: "male",
    status: "active",
    bio: "lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    msgCount: 0,
  },
  {
    _id: "u08",
    userId: "08",
    name: "Alice Johnson",
    username: "alicejohnson",
    email: "alice@example.com",
    avatar: "https://i.pravatar.cc/300",
    gender: "female",
    status: "active",
    bio: "lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    msgCount: 0,
  },
  {
    _id: "u09",
    userId: "09",
    name: "Charlie Brown",
    username: "charliebrown",
    email: "charlie@example.com",
    avatar: "https://i.pravatar.cc/300",
    gender: "male",
    status: "active",
    bio: "lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    msgCount: 7,
  },
  {
    _id: "u10",
    userId: "10",
    name: "Jane Doe",
    username: "janedoe",
    email: "jane@example.com",
    avatar: "https://i.pravatar.cc/300",
    gender: "female",
    status: "active",
    bio: "lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    msgCount: 6,
  },
  {
    _id: "u11",
    userId: "11",
    name: "Bob Smith",
    username: "bobsmith",
    email: "bob@example.com",
    avatar: "https://i.pravatar.cc/300",
    gender: "male",
    status: "active",
    bio: "lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    msgCount: 5,
  },
  {
    _id: "u12",
    userId: "12",
    name: "Alice Johnson",
    username: "alicejohnson",
    email: "alice@example.com",
    avatar: "https://i.pravatar.cc/300",
    gender: "female",
    status: "active",
    bio: "lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    msgCount: 4,
  },
  {
    _id: "u13",
    userId: "13",
    name: "Charlie Brown",
    username: "charliebrown",
    email: "charlie@example.com",
    avatar: "https://i.pravatar.cc/300",
    gender: "male",
    status: "active",
    bio: "lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    msgCount: 3,
  },
];

export const conversations = [
  {
    _id: "c01",
    senderId: "u01",
    receiverId: "u02",
    messages: [
      {
        _id: "m01",
        senderId: "u01",
        receiverId: "u02",
        text: "Hello, how are you?",
        createdAt: new Date(),
      },
      {
        _id: "m02",
        senderId: "u02",
        receiverId: "u01",
        text: "I'm fine, thanks. How about you?",
        createdAt: new Date(),
      },
      {
        _id: "m03",
        senderId: "u01",
        receiverId: "u02",
        text: "I'm also doing well. What about you?",
        createdAt: new Date(),
      },
      {
        _id: "m04",
        senderId: "u02",
        receiverId: "u01",
        text: "I'm also doing well. What about you?",
        createdAt: new Date(),
      },
    ],
  },
];
